### ISSUE TITLE
Add a SolR service

### ISSUE THREAD

**Issue by oalam** [Hurence/logisland#345] opened 2017-11-20 10:26 UTC
Same features as elasticsearch service

- make one search-service-api for ES/SOLR
- implementation for SOLR 5.5.5
- implementation for SOLR 6.6.2
- add tests on embedded server

**Comment by mathieu-rossignol** [comment] 2017-11-27 08:05
Duplicate of https://github.com/Hurence/logisland/issues/345, closing the old one.

**Comment by mathieu-rossignol** [comment] 2017-11-27 08:08
Support for routing equivalent would be nice. By the way does the ES service support for routing ? If not one should open an issue for tracking. Routing is great to speeding up ES search requests as it co-locate documents with a same id on the same ES node.

**Closed** 2018-01-25 10:38 UTC
Labels: feature, processor
